tap 'homebrew/cask'

# bash
brew 'bash'
brew 'bash-completion@2'

# git
brew 'git'
brew 'git-delta'
brew 'gh'

# Command line tools
brew 'bat'
brew 'bats'
brew 'direnv'
cask 'docker'
brew 'dockutil'
brew 'exa'
brew 'exercism'
brew 'fd'
brew 'fzf'
tap 'golangci/tap'
brew 'golangci/tap/golangci-lint'
brew 'graphviz'
tap 'heroku/brew'
brew 'heroku/brew/heroku'
brew 'httpie'
brew 'jq'
brew 'kubectl'
brew 'make'
brew 'readline'
brew 'ripgrep'
brew 'shellcheck'
brew 'tldr'
brew 'travis'
brew 'watch'

# Language version managers
brew 'gimme'    # Go
brew 'nvm'      # Node.js
brew 'rbenv'    # Ruby

# Editors
cask 'goland'
brew 'nvim'
cask 'visual-studio-code'

# Menu bar apps
cask 'dropbox'
cask 'flycut'
cask 'itsycal'
cask 'rectangle'

# Apps
cask '1password'
cask 'brave-browser'
cask 'iterm2'
cask 'slack'
cask 'tableplus'
cask 'zoom'
