#!/usr/bin/env bash

set -euo pipefail

main() {
  start

  update_macos
  update_homebrew
  update_homebrew_bundle
  run_post_install_scripts

  finish
}

log() {
  local message=$1
  echo -e "\033[1m--> ${message}\033[0m"
}

start() {
  log "Start setup"
}

update_macos() {
  log "Update macOS"
  softwareupdate --install --all
}

update_homebrew() {
  if hash brew &> /dev/null
  then
    log "Update Homebrew"
    brew update
  else
    log "Install Homebrew"
    /usr/bin/env bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi
}

update_homebrew_bundle() {
  log "Update Homebrew Bundle"
  brew bundle --global --verbose
}

run_post_install_scripts() {
  for installer in "$HOME/.config/post_install"/*.bash
  do
    command "$installer"
  done
}

finish() {
  log "Finished setup"
  echo
}

main
