#!/usr/bin/env bash

set -euo pipefail

main() {
  log "Start update"

  update_macos
  update_homebrew
  update_homebrew_bundle
  run_post_install_scripts

  log "Finished update"
}

log() {
  local message=$1
  echo -e "\033[1m--> ${message}\033[0m"
}

update_macos() {
  log "Update macOS"
  softwareupdate --install --all
}

update_homebrew() {
  log "Update Homebrew"
  brew update
}

update_homebrew_bundle() {
  log "Update Homebrew Bundle"
  brew bundle --global --verbose
}

run_post_install_scripts() {
  for installer in "$HOME/.brew/post_install"/*.bash
  do
    # shellcheck disable=SC1090
    source "$installer"
  done
}

main
